const COUNTRIES = [
  { name: "Pakistan", code: "+92" },
  { name: "United Arab Emirates", code: "+971" },
  { name: "Saudi Arabia", code: "+966" },
  { name: "United States", code: "+1" },
  { name: "USA", code: "+1" },
  { name: "United Kingdom", code: "+44" },
  { name: "India", code: "+91" },
  { name: "China", code: "+86" },
  { name: "Malaysia", code: "+60" },
  { name: "Indonesia", code: "+62" },
  { name: "Singapore", code: "+65" },
  { name: "Turkey", code: "+90" },
  { name: "Germany", code: "+49" },
  { name: "France", code: "+33" },
  { name: "Canada", code: "+1" },
  { name: "Australia", code: "+61" }
];

const INDUSTRIES = [
  "Carbon Markets",
  "Renewable Energy",
  "Green Hydrogen",
  "Sustainable Aviation Fuel",
  "Biochar",
  "Manufacturing",
  "Oil & Gas",
  "Finance",
  "Banking",
  "Consulting",
  "Technology",
  "Real Estate",
  "Agriculture",
  "Construction",
  "Mining",
  "Transportation",
  "Government",
  "NGO",
  "Education",
  "Healthcare",
  "Other"
];

const JOB_TITLES = [
  "Founder",
  "Owner",
  "CEO",
  "Managing Director",
  "Director",
  "Executive Director",
  "Chairman",
  "President",
  "Partner",
  "Manager",
  "Project Manager",
  "Business Development Manager",
  "Consultant",
  "Engineer",
  "Developer",
  "Analyst",
  "Investor",
  "Researcher",
  "Sales Manager",
  "Operations Manager",
  "Other"
];