const COUNTRIES = [
  { name: "Pakistan", code: "+92", flag: "🇵🇰" },
  { name: "United Arab Emirates", code: "+971", flag: "🇦🇪" },
  { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
  { name: "United States", code: "+1", flag: "🇺🇸" },
  { name: "USA", code: "+1", flag: "🇺🇸" },
  { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
  { name: "India", code: "+91", flag: "🇮🇳" },
  { name: "China", code: "+86", flag: "🇨🇳" },
  { name: "Malaysia", code: "+60", flag: "🇲🇾" },
  { name: "Indonesia", code: "+62", flag: "🇮🇩" },
  { name: "Singapore", code: "+65", flag: "🇸🇬" },
  { name: "Turkey", code: "+90", flag: "🇹🇷" },
  { name: "Germany", code: "+49", flag: "🇩🇪" },
  { name: "France", code: "+33", flag: "🇫🇷" },
  { name: "Canada", code: "+1", flag: "🇨🇦" },
  { name: "Australia", code: "+61", flag: "🇦🇺" },
  { name: "Oman", code: "+968", flag: "🇴🇲" },
  { name: "Qatar", code: "+974", flag: "🇶🇦" },
  { name: "Bahrain", code: "+973", flag: "🇧🇭" },
  { name: "Kuwait", code: "+965", flag: "🇰🇼" },
  { name: "Jordan", code: "+962", flag: "🇯🇴" },
  { name: "Egypt", code: "+20", flag: "🇪🇬" },
  { name: "South Africa", code: "+27", flag: "🇿🇦" },
  { name: "Kenya", code: "+254", flag: "🇰🇪" },
  { name: "Nigeria", code: "+234", flag: "🇳🇬" },
  { name: "Brazil", code: "+55", flag: "🇧🇷" },
  { name: "Mexico", code: "+52", flag: "🇲🇽" },
  { name: "Japan", code: "+81", flag: "🇯🇵" },
  { name: "South Korea", code: "+82", flag: "🇰🇷" }
];

const INDUSTRIES = [
  "Carbon Markets",
  "Renewable Energy",
  "Green Hydrogen",
  "Sustainable Aviation Fuel",
  "Biochar",
  "Manufacturing",
  "Oil & Gas",
  "Finance",
  "Banking",
  "Consulting",
  "Technology",
  "Real Estate",
  "Agriculture",
  "Construction",
  "Mining",
  "Transportation",
  "Government",
  "NGO",
  "Education",
  "Healthcare",
  "Other"
];

const JOB_TITLES = [
  "Founder",
  "Owner",
  "CEO",
  "Managing Director",
  "Director",
  "Executive Director",
  "Chairman",
  "President",
  "Partner",
  "Manager",
  "Project Manager",
  "Business Development Manager",
  "Consultant",
  "Engineer",
  "Developer",
  "Analyst",
  "Investor",
  "Researcher",
  "Sales Manager",
  "Operations Manager",
  "Other"
];
const CURRENCIES = [
  { code: "USD", symbol: "$", name: "US Dollar", flag: "🇺🇸" },
  { code: "EUR", symbol: "€", name: "Euro", flag: "🇪🇺" },
  { code: "GBP", symbol: "£", name: "British Pound", flag: "🇬🇧" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham", flag: "🇦🇪" },
  { code: "SAR", symbol: "﷼", name: "Saudi Riyal", flag: "🇸🇦" },
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial", flag: "🇴🇲" },
  { code: "QAR", symbol: "﷼", name: "Qatari Riyal", flag: "🇶🇦" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar", flag: "🇰🇼" },
  { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar", flag: "🇧🇭" },
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee", flag: "🇵🇰" },
  { code: "INR", symbol: "₹", name: "Indian Rupee", flag: "🇮🇳" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", flag: "🇨🇳" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", flag: "🇯🇵" },
  { code: "SGD", symbol: "S$", name: "Singapore Dollar", flag: "🇸🇬" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", flag: "🇲🇾" }
];
const REGISTRIES = [
  "Verra (VCS)",
  "Gold Standard",
  "ACR",
  "Climate Action Reserve",
  "Puro.Earth",
  "Global Carbon Council",
  "ART TREES",
  "CDM",
  "CAR",
  "Plan Vivo"
];
const METHODOLOGIES = [
  "Afforestation",
  "Reforestation",
  "Blue Carbon",
  "Biochar",
  "Methane Capture",
  "Landfill Gas",
  "Renewable Energy",
  "Solar",
  "Wind",
  "Hydro",
  "Green Hydrogen",
  "Industrial Efficiency",
  "Carbon Removal",
  "Direct Air Capture"
];
const PROJECT_TYPES = [
  "Solar Energy",
  "Wind Energy",
  "Biochar",
  "Forestry",
  "Blue Carbon",
  "Methane Capture",
  "Waste Management",
  "Energy Efficiency",
  "Green Hydrogen",
  "Sustainable Aviation Fuel",
  "Carbon Capture",
  "Cookstoves",
  "Other"
];

const CREDIT_TYPES = [
  "Carbon Removal",
  "Avoided Emissions",
  "Renewable Energy Credits",
  "Nature-Based Credits",
  "Technology-Based Credits",
  "Blue Carbon Credits",
  "Other"
];
