export const CANONICAL_PREDICATES = Object.freeze({

  SUPPORTS: "SUPPORTS",

  TARGETS: "TARGETS",

  REQUIRES: "REQUIRES",

  INCLUDES: "INCLUDES",

  FOCUSES_ON: "FOCUSES_ON",

  HAS_OBJECTIVE: "HAS_OBJECTIVE",

  AIMS_TO: "AIMS_TO",

  REDUCES: "REDUCES",

  INCREASES: "INCREASES",

  GENERATES: "GENERATES",

  INVESTS_IN: "INVESTS_IN",

  ENABLES: "ENABLES",

  /* CBRIL regulatory / lifecycle relations */
  SUPERSEDES: "SUPERSEDES",
  AMENDS: "AMENDS",
  IMPLEMENTS: "IMPLEMENTS",
  REFERENCES: "REFERENCES",
  APPLIES_TO: "APPLIES_TO",
  RELATED_TO: "RELATED_TO",
  ALIGNS_WITH: "ALIGNS_WITH",
  BASED_ON: "BASED_ON",
  DERIVED_FROM: "DERIVED_FROM",
  PART_OF: "PART_OF",
  REPORTED_UNDER: "REPORTED_UNDER",
  GOVERNED_BY: "GOVERNED_BY",
  ISSUED_BY: "ISSUED_BY",
  SUPPORTED_BY: "SUPPORTED_BY",
  CONFLICTS_WITH: "CONFLICTS_WITH",
  DEPENDS_ON: "DEPENDS_ON",
  REGULATES: "REGULATES",
  PROHIBITS: "PROHIBITS",
  IS_A: "IS_A",

});
