import {
  ENTITY_TYPES,
} from "./entityTypes.js";

export const CONCEPT_HIERARCHY =
  Object.freeze({

    "Energy": {

      entityType:
        ENTITY_TYPES.CATEGORY,

      parent: null,

      aliases: [],

      description:
        "Primary energy domain.",

    },

    "Renewable Energy": {

      entityType:
        ENTITY_TYPES.CATEGORY,

      parent:
        "Energy",

      aliases: [
        "Renewables",
      ],

      description:
        "Energy from renewable resources.",

    },

    "Low Carbon Technology": {

      entityType:
        ENTITY_TYPES.CATEGORY,

      parent:
        "Energy",

      aliases: [],

      description:
        "Technologies reducing carbon emissions.",

    },

    "Clean Fuel": {

      entityType:
        ENTITY_TYPES.CATEGORY,

      parent:
        "Low Carbon Technology",

      aliases: [],

      description:
        "Low emission fuels.",

    },

    "Hydrogen": {

      entityType:
        ENTITY_TYPES.TECHNOLOGY,

      parent:
        "Clean Fuel",

      aliases: [],

      description:
        "Hydrogen energy technologies.",

    },

    "Green Hydrogen": {

      entityType:
        ENTITY_TYPES.TECHNOLOGY,

      parent:
        "Hydrogen",

      aliases: [
        "Renewable Hydrogen",
      ],

      description:
        "Hydrogen produced using renewable electricity.",

    },

    "Solar PV": {

      entityType:
        ENTITY_TYPES.TECHNOLOGY,

      parent:
        "Renewable Energy",

      aliases: [
        "Solar",
      ],

      description:
        "Photovoltaic technology.",

    },

    "Wind Power": {

      entityType:
        ENTITY_TYPES.TECHNOLOGY,

      parent:
        "Renewable Energy",

      aliases: [
        "Wind Energy",
      ],

      description:
        "Electricity generated by wind turbines.",

    },

    "CCUS": {

      entityType:
        ENTITY_TYPES.TECHNOLOGY,

      parent:
        "Low Carbon Technology",

      aliases: [

        "Carbon Capture",

        "Carbon Capture Utilization and Storage",

        "Carbon Capture and Storage",

      ],

      description:
        "Carbon Capture, Utilization and Storage.",

    },

  });
