export const ENTITY_TYPES =
  Object.freeze({

    COUNTRY: "COUNTRY",

    ORGANIZATION: "ORGANIZATION",

    POLICY: "POLICY",

    STRATEGY: "STRATEGY",

    PERSON: "PERSON",

    TECHNOLOGY: "TECHNOLOGY",

    ENERGY_SOURCE: "ENERGY_SOURCE",

    CARBON_PROJECT: "CARBON_PROJECT",

    FINANCIAL_INSTRUMENT: "FINANCIAL_INSTRUMENT",

    UNIT: "UNIT",

    CATEGORY: "CATEGORY",

    SECTOR: "SECTOR",

    PROGRAM: "PROGRAM",

    FRAMEWORK: "FRAMEWORK",

    STANDARD: "STANDARD",

  });
